version: "2"
run:
  go: "1.25"
linters:
  enable:
    - thelper
    - tparallel
    - unconvert
    - unparam
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
      - internal/db/gen
formatters:
  enable:
    - gofumpt
  settings:
    gofumpt:
      module-path: github.com/emprcl/spor
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - internal/db/gen
